name: directional-website
channels:
  - conda-forge
dependencies:
  - python=3.10
  - mkdocs=1.2.4
  - mkdocs-material=8.2.7
  - mkdocs-macros-plugin=0.7.0
  - pygments=2.11.2
  - pymdown-extensions=9.3
  - pip=22.0.4
  - pip:
      - mkdocs-redirects==1.0.3
      - mkdocs-minify-plugin==0.4.0
      - LinkChecker==10.1.0
      - "--editable=git+https://github.com/jdumas/figureAltCaption@c1eb51cffa0c500d5f7c9b78bd3b5e752e14aee9#egg=figureAltCaption"
